spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///G:/ESTUDIO/controla-tus-gastos/ignore
          #uri: /media/caobandoc/DATAEx/ESTUDIO/controla-tus-gastos/ignore
server:
  port: 8888